Repository HicServices/RDMP, pull requests merged in 2022-05, with the labels that each got.

#1130 Auto resize usersetting
  CHANGELOG.md
  Rdmp.UI/ChecksUI/ChecksUI.cs
  Rdmp.UI/Progress/ProgressUI.Designer.cs
  Rdmp.UI/Progress/ProgressUI.cs
  Rdmp.UI/SimpleDialogs/UserSettingsUI.Designer.cs
  Rdmp.UI/SimpleDialogs/UserSettingsUI.cs
  Reusable/ReusableLibraryCode/Settings/UserSettings.cs
Labels: enhancement, usability

#1161 Disable autorun sql in view data tabs
  CHANGELOG.md
  Rdmp.UI/DataViewing/ViewSQLAndResultsWithDataGridUI.Designer.cs
  Rdmp.UI/DataViewing/ViewSQLAndResultsWithDataGridUI.cs
  Rdmp.UI/DataViewing/ViewSQLAndResultsWithDataGridUI.resx
  Rdmp.UI/SimpleDialogs/UserSettingsUI.Designer.cs
  Rdmp.UI/SimpleDialogs/UserSettingsUI.cs
  Reusable/ReusableLibraryCode/Settings/UserSettings.cs
Labels: enhancement

#1198 Cic UI refactor
  Rdmp.Core/CohortCreation/CohortIdentificationConfigurationUICommon.cs
  Rdmp.Core/CohortCreation/Execution/CohortCompiler.cd
  Rdmp.UI/SubComponents/CohortIdentificationConfigurationUI.cs
  Tools/rdmp/CommandLine/Gui/ConsoleGuiActivator.cs
  Tools/rdmp/CommandLine/Gui/ConsoleGuiCohortIdentificationConfigurationUI.Designer.cs
  Tools/rdmp/CommandLine/Gui/ConsoleGuiCohortIdentificationConfigurationUI.cs
  Tools/rdmp/CommandLine/Gui/ConsoleGuiContextMenuFactory.cs
  Tools/rdmp/CommandLine/Gui/ConsoleMainWindow.cs
Labels: Console
